LOGIN_SUCCESS = "Login successful."
INVALID_CREDENTIALS = "Invalid email or password."
INACTIVE_USER = "User account is inactive."
UNAUTHORIZED = "Could not validate credentials."
CURRENT_USER_RETRIEVED = "Current user retrieved successfully."