"""add_user_id_to_trips

Revision ID: 58ffdcc0266d
Revises: e48986eb2149
Create Date: 2026-07-31 00:06:51.723131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ffdcc0266d'
down_revision: Union[str, Sequence[str], None] = 'e48986eb2149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'user_id')
    # ### end Alembic commands ###
